"""
CoupleWealth — PDF Report Generator
8-page couple financial report using fpdf2.
"""

from fpdf import FPDF
from datetime import datetime
import io


class CoupleWealthReport(FPDF):
    """Custom PDF with CoupleWealth branding."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, "CoupleWealth Financial Report", align="L")
            self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 16, 200, 16)
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by CoupleWealth AI | Confidential", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(15, 25, 35)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def key_value(self, key: str, value: str, bold_value=False):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(80, 80, 80)
        self.cell(80, 7, key)
        self.set_font("Helvetica", "B" if bold_value else "", 10)
        self.set_text_color(15, 25, 35)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def separator(self):
        self.ln(3)
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)


def _fmt(amount: int) -> str:
    """Format amount in Indian number system."""
    if amount < 0:
        return f"-{_fmt(abs(amount))}"
    s = str(int(amount))
    if len(s) <= 3:
        return s
    result = s[-3:]
    s = s[:-3]
    while s:
        result = s[-2:] + "," + result
        s = s[:-2]
    return result


def generate_couple_report(analysis: dict) -> bytes:
    """Generate complete 8-page PDF report."""
    pdf = CoupleWealthReport()

    _page_cover(pdf, analysis)
    _page_health_score(pdf, analysis)
    _page_tax(pdf, analysis)
    _page_investments(pdf, analysis)
    _page_goals(pdf, analysis)
    _page_insurance(pdf, analysis)
    _page_market(pdf, analysis)
    _page_actions(pdf, analysis)

    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()


def _page_cover(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(232, 184, 75)  # Gold
    pdf.ln(40)
    pdf.cell(0, 15, "CoupleWealth", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Joint Financial Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    name_a = data.get("partner_a", {}).get("name", "Partner A")
    name_b = data.get("partner_b", {}).get("name", "Partner B")
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 25, 35)
    pdf.cell(0, 10, f"{name_a} & {name_b}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, f"Generated on {datetime.now().strftime('%B %d, %Y')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)

    headline = data.get("headline_saving", 0)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(232, 184, 75)
    pdf.cell(0, 20, f"Rs {_fmt(headline)}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "annual recovery identified", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)
    breakdown = data.get("headline_breakdown", {})
    items = [
        ("Tax Saving", breakdown.get("tax_saving", 0)),
        ("Investment Gain", breakdown.get("investment_gain", 0)),
        ("Insurance Saving", breakdown.get("insurance_saving", 0)),
        ("Market Alpha", breakdown.get("market_alpha_recovery", 0)),
    ]
    pdf.set_font("Helvetica", "", 10)
    for label, amt in items:
        pdf.set_text_color(80, 80, 80)
        pdf.cell(95, 7, f"  {label}: Rs {_fmt(amt)}", align="L")
    pdf.ln(7)
    for i, (label, amt) in enumerate(items):
        if i >= 2:
            pdf.set_text_color(80, 80, 80)
            pdf.cell(95, 7, f"  {label}: Rs {_fmt(amt)}", align="L")
    pdf.ln(10)


def _page_health_score(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Money Health Score")

    hs = data.get("health_score", {})
    total = hs.get("total", 0)
    grade = hs.get("grade", "D")
    projected = hs.get("projected_score", 0)

    pdf.set_font("Helvetica", "B", 48)
    pdf.set_text_color(232, 184, 75)
    pdf.cell(95, 30, str(total), align="C")
    pdf.set_font("Helvetica", "B", 48)
    pdf.cell(95, 30, grade, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(16, 185, 129)
    pdf.cell(0, 8, f"After recommendations: {projected}/100", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.separator()
    for dim in hs.get("dimensions", []):
        pdf.key_value(
            dim.get("name", ""),
            f"{dim.get('score', 0)} / {dim.get('max', 0)} — {dim.get('tip', '')}",
        )


def _page_tax(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Tax Optimization")

    for pk in ["partner_a", "partner_b"]:
        p = data.get(pk, {})
        name = p.get("name", pk)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 25, 35)
        pdf.cell(0, 8, name, new_x="LMARGIN", new_y="NEXT")

        pdf.key_value("Recommended Regime", p.get("recommended_regime", "auto").upper(), True)
        pdf.key_value("Current Tax", f"Rs {_fmt(p.get('current_tax', 0))}")
        pdf.key_value("Optimized Tax", f"Rs {_fmt(p.get('optimized_tax', 0))}")
        pdf.key_value("Tax Saving", f"Rs {_fmt(p.get('tax_saving', 0))}", True)
        pdf.key_value("HRA Exemption", f"Rs {_fmt(p.get('hra_exemption_available', 0))}")
        pdf.separator()

    pdf.key_value("HRA Winner", data.get("hra_winner", "N/A"), True)
    pdf.key_value("HRA Annual Saving", f"Rs {_fmt(data.get('hra_annual_saving', 0))}", True)


def _page_investments(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Investment Plan")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    explanation = data.get("regime_explanation", "")
    if explanation:
        pdf.multi_cell(0, 6, explanation)
        pdf.ln(5)

    actions = [a for a in data.get("priority_actions", []) if "SIP" in a.get("title", "") or "NPS" in a.get("title", "") or "80C" in a.get("title", "") or "ELSS" in a.get("title", "")]
    for a in actions[:5]:
        pdf.key_value(a["title"], f"Saves Rs {_fmt(a.get('annual_saving', 0))}/yr")


def _page_goals(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Goal Roadmap")

    for g in data.get("goal_plans", []):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 25, 35)
        status = "[ON TRACK]" if g.get("on_track") else "[NEEDS ATTENTION]"
        pdf.cell(0, 7, f"{g['name']} {status}", new_x="LMARGIN", new_y="NEXT")
        pdf.key_value("Target Year", str(g.get("target_year", "")))
        pdf.key_value("Present Cost", f"Rs {_fmt(g.get('present_cost', 0))}")
        pdf.key_value("Future Cost", f"Rs {_fmt(g.get('future_cost', 0))}")
        pdf.key_value("Required SIP", f"Rs {_fmt(g.get('required_monthly_sip', 0))}/month")
        pdf.separator()

    ret = data.get("retirement", {})
    if ret:
        pdf.section_title("FIRE Projection")
        pdf.key_value("FIRE Number", f"Rs {_fmt(ret.get('fire_number', 0))}")
        pdf.key_value("Projected Corpus", f"Rs {_fmt(ret.get('projected_corpus', 0))}")
        pdf.key_value("Current Retirement Age", str(ret.get("current_retirement_age", "")))
        pdf.key_value("Optimized Retirement Age", str(ret.get("optimized_retirement_age", "")))


def _page_insurance(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Insurance Audit")

    ins = data.get("insurance", {})
    for pk, label in [("partner_a", "Partner A"), ("partner_b", "Partner B")]:
        p = ins.get(pk, {})
        name = data.get(pk, {}).get("name", label)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, name, new_x="LMARGIN", new_y="NEXT")
        pdf.key_value("Required Term Cover", f"Rs {_fmt(p.get('required_term', 0))}")
        pdf.key_value("Existing Cover", f"Rs {_fmt(p.get('existing_term', 0))}")
        pdf.key_value("Gap", f"Rs {_fmt(p.get('gap', 0))}", True)
        pdf.separator()

    pdf.key_value("Health Cover Gap", f"Rs {_fmt(ins.get('health_cover_gap', 0))}")
    pdf.key_value("80D Saving Available", f"Rs {_fmt(ins.get('annual_80d_saving_available', 0))}/yr", True)


def _page_market(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Market Intelligence")

    portfolio = data.get("portfolio", {})
    pdf.key_value("Portfolio Value", f"Rs {_fmt(portfolio.get('total_value', 0))}")
    pdf.key_value("Your XIRR", f"{portfolio.get('xirr', 0):.1f}%")
    pdf.key_value("Benchmark XIRR", f"{portfolio.get('benchmark_xirr', 0):.1f}%")
    pdf.key_value("Expense Drag", f"Rs {_fmt(portfolio.get('expense_drag_annual', 0))}/yr")
    pdf.separator()

    signals = data.get("market_signals", [])
    if signals:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Opportunity Alerts", new_x="LMARGIN", new_y="NEXT")
        for s in signals[:5]:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            impact = s.get("annual_impact", 0)
            desc = s.get("description", "")
            pdf.multi_cell(0, 5, f"- {desc} (Rs {_fmt(impact)}/yr)")
            pdf.ln(2)


def _page_actions(pdf: CoupleWealthReport, data: dict):
    pdf.add_page()
    pdf.section_title("Priority Action Plan")

    for action in data.get("priority_actions", [])[:10]:
        rank = action.get("rank", 0)
        title = action.get("title", "")
        detail = action.get("detail", "")
        saving = action.get("annual_saving", 0)
        effort = action.get("effort", "")
        timeframe = action.get("timeframe", "")

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 25, 35)
        pdf.cell(0, 7, f"#{rank}. {title}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, detail)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(16, 185, 129)
        pdf.cell(60, 6, f"Saves Rs {_fmt(saving)}/yr")
        pdf.set_text_color(80, 80, 80)
        pdf.cell(40, 6, f"Effort: {effort}")
        pdf.cell(0, 6, f"Timeline: {timeframe}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
