"""
SOW — Premium PDF Report Generator (v2, bulletproof)
8-section financial dossier with clean layout.
"""

from fpdf import FPDF
from datetime import datetime
import io


# ── Color palette ─────────────────────────────────────────────
GOLD     = (234, 179,   8)
DARK     = ( 15,  25,  35)
MID      = ( 71,  85, 105)
LIGHT_BG = (248, 250, 252)
WHITE    = (255, 255, 255)
SUCCESS  = ( 16, 185, 129)
DANGER   = (239,  68,  68)
BORDER   = (226, 232, 240)


def _safe(text: str) -> str:
    """Robustly strip non-Latin-1 chars and substitute complex symbols to prevent PDF crashes."""
    if not isinstance(text, str):
        text = str(text)
    # Map high-Unicode characters to their standard Latin-1 equivalents
    replacements = {
        '₹': 'Rs.',     # Indian Rupee symbol
        '\u20b9': 'Rs.',# Unicode Rupee
        '\u2014': '-',  # em-dash
        '\u2013': '-',  # en-dash
        '\u2018': "'",  # curly single quote
        '\u2019': "'",  # curly single quote
        '\u201c': '"',  # curly double quote
        '\u201d': '"',  # curly double quote
    }
    for char, rep in replacements.items():
        text = text.replace(char, rep)
    return text.encode('latin-1', errors='replace').decode('latin-1')


def _fmt(amount) -> str:
    """Indian number format without currency prefix."""
    try:
        amount = int(float(amount or 0))
    except Exception:
        return "0"
    if amount < 0:
        return f"-{_fmt(-amount)}"
    s = str(amount)
    if len(s) <= 3:
        return s
    result = s[-3:]
    s = s[:-3]
    while s:
        result = s[-2:] + "," + result
        s = s[:-2]
    return result


def _inr(amount) -> str:
    return f"Rs {_fmt(amount)}"


class SOWReport(FPDF):
    """SOW branded PDF class."""

    def header(self):
        if self.page_no() == 1:
            return
        self.set_fill_color(*DARK)
        self.rect(0, 0, 210, 10, 'F')
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*GOLD)
        self.set_xy(10, 2)
        self.cell(150, 6, _safe("SOW - Strategy Optimization Workspace"), align="L")
        self.set_text_color(*WHITE)
        self.set_xy(140, 2)
        self.cell(60, 6, f"Page {self.page_no()}", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MID)
        self.cell(0, 6, "Generated by SOW Intelligence Engine  |  CONFIDENTIAL", align="C")

    def gold_bar(self, title: str, subtitle: str = ""):
        """Full-width golden section header."""
        y = self.get_y()
        self.set_fill_color(*GOLD)
        self.rect(10, y, 190, 11, 'F')
        self.set_xy(14, y)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*DARK)
        self.cell(0, 11, _safe(title.upper()), new_x="LMARGIN", new_y="NEXT")
        if subtitle:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*MID)
            self.cell(0, 5, _safe(subtitle), new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def kv(self, label: str, value: str, val_bold=False, val_color=None):
        """Key-value row."""
        self.set_x(12)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MID)
        self.cell(85, 7, _safe(label))
        self.set_font("Helvetica", "B" if val_bold else "", 9)
        self.set_text_color(*(val_color or DARK))
        self.cell(0, 7, _safe(value), new_x="LMARGIN", new_y="NEXT")

    def row_cells(self, cols, widths, bold=False, header=False):
        """Table row."""
        if header:
            self.set_fill_color(*LIGHT_BG)
            self.rect(10, self.get_y(), 190, 8, 'F')
        self.set_x(12)
        for i, (text, w) in enumerate(zip(cols, widths)):
            self.set_font("Helvetica", "B" if (bold or header) else "", 8)
            self.set_text_color(*MID if header else DARK)
            self.cell(w, 8, _safe(str(text))[:38], align="R" if i > 0 else "L")
        self.ln(8)

    def rule(self):
        """Thin horizontal divider."""
        self.ln(2)
        self.set_draw_color(*BORDER)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def stat_box(self, x, y, w, h, label, value, col=None):
        """Small metric box."""
        self.set_fill_color(*LIGHT_BG)
        self.set_draw_color(*BORDER)
        self.rect(x, y, w, h, 'FD')
        self.set_xy(x + 2, y + 2)
        self.set_font("Helvetica", "B", 6)
        self.set_text_color(*MID)
        self.cell(w - 4, 5, _safe(label.upper())[:20], align="C")
        self.set_xy(x + 2, y + 7)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*(col or DARK))
        self.cell(w - 4, 7, _safe(str(value))[:16], align="C")


# ── Page functions ─────────────────────────────────────────────

def _cover(pdf: SOWReport, d: dict):
    pdf.add_page()

    # Dark top band
    pdf.set_fill_color(*DARK)
    pdf.rect(0, 0, 210, 85, 'F')

    # SOW monogram
    pdf.set_font("Helvetica", "B", 56)
    pdf.set_text_color(*GOLD)
    pdf.set_xy(0, 12)
    pdf.cell(210, 28, "SOW", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(180, 180, 180)
    pdf.set_x(0)
    pdf.cell(210, 7, "Strategy Optimization Workspace", align="C", new_x="LMARGIN", new_y="NEXT")

    name_a = d.get("partner_a", {}).get("name", "Partner A")
    name_b = d.get("partner_b", {}).get("name", "Partner B")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*WHITE)
    pdf.set_x(0)
    pdf.cell(210, 10, _safe(f"{name_a}  &  {name_b}"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GOLD)
    pdf.set_x(0)
    pdf.cell(210, 7, _safe(datetime.now().strftime("%B %d, %Y")), align="C", new_x="LMARGIN", new_y="NEXT")

    # Headline saving
    pdf.set_y(93)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*MID)
    pdf.cell(210, 6, "ANNUAL RECOVERY IDENTIFIED", align="C", new_x="LMARGIN", new_y="NEXT")

    headline = d.get("headline_saving", 0)
    pdf.set_font("Helvetica", "B", 38)
    pdf.set_text_color(*GOLD)
    pdf.cell(210, 20, _safe(f"Rs {_fmt(headline)}"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MID)
    pdf.cell(210, 5, "per financial year", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # 4 stat boxes in a row
    bd = d.get("headline_breakdown", {})
    boxes = [
        ("Tax Saving",      bd.get("tax_saving", 0),        GOLD),
        ("Invest Gain",     bd.get("investment_gain", 0),   SUCCESS),
        ("Insurance",       bd.get("insurance_saving", 0),  (59, 130, 246)),
        ("Market Alpha",    bd.get("market_alpha_recovery", 0), MID),
    ]
    bxs = 12
    by = pdf.get_y()
    for label, val, col in boxes:
        pdf.stat_box(bxs, by, 45, 22, label, _inr(val), col)
        bxs += 47
    pdf.set_y(by + 28)

    # Engine
    engine = d.get("engine", "Local Math Engine")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*SUCCESS if "Ollama" in engine else MID)
    pdf.cell(210, 6, _safe(f"Intelligence Engine: {engine}"), align="C", new_x="LMARGIN", new_y="NEXT")

    enc = _safe(d.get("encouragement", ""))
    if enc:
        pdf.ln(6)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MID)
        pdf.set_x(20)
        pdf.multi_cell(170, 5, f'"{enc}"', align="C")

    # TOC
    pdf.ln(8)
    pdf.set_fill_color(*LIGHT_BG)
    pdf.rect(10, pdf.get_y(), 190, 7, 'F')
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*MID)
    sections = "Health Score - Tax - Investments - Goals - Insurance - Market - Action Plan"
    pdf.cell(210, 7, _safe(f"CONTENTS:  {sections}"), align="C", new_x="LMARGIN", new_y="NEXT")


def _health(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Money Health Score", "6-dimensional financial wellness audit")

    hs    = d.get("health_score", {})
    total = hs.get("total", 0)
    grade = hs.get("grade", "N/A")
    proj  = hs.get("projected_score", total)

    # Big numbers
    pdf.set_font("Helvetica", "B", 60)
    pdf.set_text_color(*GOLD)
    pdf.cell(95, 32, str(total), align="C")
    pdf.cell(95, 32, grade, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*SUCCESS)
    pdf.cell(0, 7, f"After recommendations: {proj}/100  (+{proj - total} points)", align="C",
             new_x="LMARGIN", new_y="NEXT")
    pdf.rule()

    dims = hs.get("dimensions", [])
    if isinstance(dims, dict):
        # Convert dict to list of dicts if needed
        dims = [{"name": k.replace("_", " ").title(), **v} for k, v in dims.items() if isinstance(v, dict)]

    for dim in dims:
        if not isinstance(dim, dict): continue
        name  = dim.get("name", "Dimension")
        score = dim.get("score", 0)
        maxi  = dim.get("max", 20)
        tip   = dim.get("tip", "")
        pct   = min(1.0, float(score) / maxi) if maxi else 0

        # Row
        pdf.set_x(12)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*DARK)
        pdf.cell(80, 7, name)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*MID)
        pdf.cell(25, 7, f"{score}/{maxi}", align="R")

        # Mini bar
        bx = 120
        by = pdf.get_y() + 2
        pdf.set_fill_color(*BORDER)
        pdf.rect(bx, by, 70, 4, 'F')
        col = SUCCESS if pct >= 0.7 else GOLD if pct >= 0.4 else DANGER
        pdf.set_fill_color(*col)
        pdf.rect(bx, by, 70 * pct, 4, 'F')
        pdf.ln(7)

        if tip:
            pdf.set_x(14)
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(*MID)
            pdf.cell(0, 4, _safe(f"-> {tip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)


def _tax(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Tax Optimization", "Old vs New regime analysis & HRA arbitrage")

    for pk in ["partner_a", "partner_b"]:
        p    = d.get(pk, {})
        name = p.get("name", pk.replace("_", " ").title())

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*DARK)
        pdf.cell(0, 8, _safe(name), new_x="LMARGIN", new_y="NEXT")

        pdf.row_cells(["Metric", "Value"], [130, 58], header=True)
        for label, val in [
            ("Recommended Regime",   _safe(p.get("recommended_regime", "N/A").upper())),
            ("Current Annual Tax",   _inr(p.get("current_tax", 0))),
            ("Optimized Annual Tax", _inr(p.get("optimized_tax", 0))),
            ("Annual Tax Saving",    _inr(p.get("tax_saving", 0))),
            ("HRA Exemption",        _inr(p.get("hra_exemption_available", 0))),
        ]:
            pdf.row_cells([_safe(label), _safe(val)], [130, 58])
        pdf.ln(4)

    pdf.rule()
    pdf.kv("HRA Best Claimant",  _safe(d.get("hra_winner", "N/A")), val_bold=True, val_color=GOLD)
    pdf.kv("HRA Annual Saving",  _inr(d.get("hra_annual_saving", 0)), val_bold=True, val_color=SUCCESS)

    explanation = _safe(d.get("regime_explanation", ""))
    if explanation:
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*GOLD)
        pdf.cell(0, 5, "AI REGIME RECOMMENDATION", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MID)
        pdf.set_x(12)
        pdf.multi_cell(186, 5, explanation[:400])


def _investments(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Investment Strategy", "SIP allocation, NPS & 80C optimization")

    a_name = d.get("partner_a", {}).get("name", "Partner A")
    b_name = d.get("partner_b", {}).get("name", "Partner B")
    a_save = d.get("partner_a", {}).get("tax_saving", 0)
    b_save = d.get("partner_b", {}).get("tax_saving", 0)

    by = pdf.get_y()
    pdf.stat_box(10,  by, 60, 22, a_name[:18], _inr(a_save), GOLD)
    pdf.stat_box(73,  by, 60, 22, b_name[:18], _inr(b_save), GOLD)
    pdf.stat_box(136, by, 64, 22, "Combined", _inr(a_save + b_save), SUCCESS)
    pdf.set_y(by + 28)
    pdf.rule()

    invest_actions = [a for a in d.get("priority_actions", [])
                      if any(kw in a.get("title", "").upper()
                             for kw in ["SIP", "NPS", "80C", "ELSS", "INVEST", "FUND"])]
    if invest_actions:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*MID)
        pdf.cell(0, 6, "RECOMMENDED INVESTMENT ACTIONS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for a in invest_actions[:6]:
            if not isinstance(a, dict): continue
            pdf.set_x(12)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*DARK)
            pdf.cell(145, 6, _safe(a.get("title", ""))[:60])
            pdf.set_text_color(*SUCCESS)
            pdf.cell(0, 6, _inr(a.get("annual_saving", 0)) + "/yr", align="R",
                        new_x="LMARGIN", new_y="NEXT")
            det = a.get("detail")
            if det:
                pdf.set_x(14)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*MID)
                pdf.multi_cell(182, 4, _safe(det)[:200])
            pdf.ln(2)

    hra = d.get("hra_explanation", "")
    if hra:
        pdf.rule()
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*GOLD)
        pdf.cell(0, 5, "HRA INTELLIGENCE", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MID)
        pdf.set_x(12)
        pdf.multi_cell(186, 5, hra[:300])


def _goals(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Goal Roadmap", "Inflation-adjusted SIP projections per milestone")

    for g in d.get("goal_plans", []):
        ok  = g.get("on_track", False)
        col = SUCCESS if ok else DANGER
        tag = "ON TRACK" if ok else "NEEDS ATTENTION"

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*DARK)
        pdf.cell(140, 7, str(g.get("name", ""))[:50])
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*col)
        pdf.cell(0, 7, f"[{tag}]", align="R", new_x="LMARGIN", new_y="NEXT")

        for label, val in [
            ("Target Year",                  str(g.get("target_year", "—"))),
            ("Present Cost",                 _inr(g.get("present_cost", 0))),
            ("Inflation-Adjusted Cost",      _inr(g.get("future_cost", 0))),
            ("Required Monthly SIP",         _inr(g.get("required_monthly_sip", 0))),
            ("Currently Allocated SIP",      _inr(g.get("current_sip_allocated", 0))),
        ]:
            pdf.kv(label, val)
        pdf.rule()

    ret = d.get("retirement", {})
    if ret:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*GOLD)
        pdf.cell(0, 7, "FIRE RETIREMENT ENGINE", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for label, val in [
            ("FIRE Independence Number",  _inr(ret.get("fire_number", 0))),
            ("Projected Corpus",          _inr(ret.get("projected_corpus", 0))),
            ("Current Retirement Age",    str(ret.get("current_retirement_age", "—"))),
            ("SOW-Optimized Retire Age",  str(ret.get("optimized_retirement_age", "—"))),
        ]:
            pdf.kv(label, val, val_bold=True)


def _insurance(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Insurance Audit", "Human Life Value (HLV) — term & health coverage")

    ins = d.get("insurance", {})
    for pk in ["partner_a", "partner_b"]:
        p    = ins.get(pk, {})
        name = d.get(pk, {}).get("name", pk.replace("_", " ").title())
        gap  = p.get("gap", 0)
        col  = DANGER if gap > 0 else SUCCESS
        tag  = f"GAP: {_inr(gap)}" if gap > 0 else "Fully Covered"

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*DARK)
        pdf.cell(140, 7, name)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*col)
        pdf.cell(0, 7, tag, align="R", new_x="LMARGIN", new_y="NEXT")

        pdf.kv("Required Term Cover",  _inr(p.get("required_term", 0)))
        pdf.kv("Existing Term Cover",  _inr(p.get("existing_term", 0)))
        pdf.kv("Coverage Deficit",     _inr(gap), val_bold=True, val_color=col)
        pdf.rule()

    pdf.kv("Combined 80D Tax Saving", _inr(ins.get("annual_80d_saving_available", 0)),
           val_bold=True, val_color=GOLD)


def _market(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Market Intelligence", "XIRR audit, expense ratio & alpha recovery")

    port = d.get("portfolio", {})
    by = pdf.get_y()
    pdf.stat_box(10,  by, 57, 22, "Portfolio XIRR",  f"{port.get('xirr', 0):.1f}%",        GOLD)
    pdf.stat_box(70,  by, 57, 22, "Benchmark XIRR",  f"{port.get('benchmark_xirr', 0):.1f}%", MID)
    pdf.stat_box(130, by, 70, 22, "Alpha Recovery",   _inr(port.get("total_market_alpha_recovery", 0)), SUCCESS)
    pdf.set_y(by + 28)
    pdf.rule()

    funds = port.get("fund_signals", [])
    if funds:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*MID)
        pdf.cell(0, 5, "ACTIVE HOLDINGS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.row_cells(["Fund", "3Y Return", "Exp Ratio", "Signal"], [95, 30, 30, 35], header=True)
        for f in funds[:8]:
            sig_col = DANGER if f.get("signal") == "Switch" else SUCCESS
            pdf.set_x(12)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*DARK)
            pdf.cell(95, 6, f.get("fund_name", "")[:38])
            pdf.cell(30, 6, f"{f.get('return_3y', 0)}%", align="R")
            pdf.cell(30, 6, f"{f.get('expense_ratio', 0)}%", align="R")
            pdf.set_text_color(*sig_col)
            pdf.cell(35, 6, f.get("signal", "Retain"), align="R", new_x="LMARGIN", new_y="NEXT")

    signals = d.get("market_signals", [])
    if signals:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*MID)
        pdf.cell(0, 5, "OPPORTUNITY ALERTS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for s in signals[:5]:
            pdf.set_x(12)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*GOLD)
            pdf.cell(140, 5, str(s.get("type", "")).replace("_", " ").upper()[:50])
            pdf.set_text_color(*SUCCESS)
            pdf.cell(0, 5, _inr(s.get("annual_impact", 0)) + "/yr", align="R",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_x(14)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*MID)
            pdf.multi_cell(180, 4, str(s.get("description", ""))[:200])
            pdf.ln(1)


def _actions(pdf: SOWReport, d: dict):
    pdf.add_page()
    pdf.gold_bar("Priority Action Plan", "AI-synthesized roadmap — ranked by annual saving impact")

    total = sum(a.get("annual_saving", 0) for a in d.get("priority_actions", []))
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*MID)
    pdf.cell(100, 7, f"Total Identified Value:  Rs {_fmt(total)} / year")
    pdf.set_text_color(*GOLD)
    pdf.cell(0, 7, d.get("engine", "Local AI"), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.rule()

    for action in d.get("priority_actions", [])[:10]:
        rank    = action.get("rank", 0)
        title   = action.get("title", "")
        detail  = action.get("detail", "")
        saving  = action.get("annual_saving", 0)
        effort  = action.get("effort", "")
        tframe  = action.get("timeframe", "")

        by = pdf.get_y()
        pdf.set_fill_color(*GOLD)
        pdf.rect(12, by, 8, 8, 'F')
        pdf.set_xy(12, by)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*DARK)
        pdf.cell(8, 8, str(rank), align="C")
        pdf.set_xy(22, by)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*DARK)
        pdf.cell(140, 8, str(title)[:55])
        pdf.set_text_color(*SUCCESS)
        pdf.cell(0, 8, _inr(saving) + "/yr", align="R", new_x="LMARGIN", new_y="NEXT")

        if detail:
            pdf.set_x(22)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*MID)
            pdf.multi_cell(176, 4, _safe(str(detail)[:250]))

        pdf.set_x(22)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*MID)
        pdf.cell(60, 5, f"Effort: {effort}")
        pdf.cell(60, 5, f"Timeline: {tframe}")
        pdf.ln(8)

    scenarios = d.get("what_if_scenarios", [])
    if scenarios:
        pdf.rule()
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*GOLD)
        pdf.cell(0, 5, "AI WHAT-IF SCENARIOS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for s in scenarios[:5]:
            pdf.set_x(12)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*DARK)
            pdf.cell(145, 6, str(s.get("scenario", ""))[:60])
            pdf.set_text_color(*SUCCESS)
            pdf.cell(0, 6, _inr(s.get("annual_saving", 0)), align="R",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_x(14)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*MID)
            pdf.multi_cell(180, 4, str(s.get("impact", ""))[:200])
            pdf.ln(2)


# ── Public entry point ────────────────────────────────────────

def generate_couple_report(analysis: dict) -> bytes:
    """Generate complete SOW PDF dossier and return raw bytes."""
    pdf = SOWReport()
    pdf.set_auto_page_break(auto=True, margin=18)

    steps = [
        ("Cover", _cover),
        ("Health", _health),
        ("Tax", _tax),
        ("Investments", _investments),
        ("Goals", _goals),
        ("Insurance", _insurance),
        ("Market", _market),
        ("Actions", _actions),
    ]

    for name, func in steps:
        try:
            func(pdf, analysis)
        except Exception as e:
            # Fallback if a page fails to render
            print(f"PDF Block '{name}' failed: {e}")
            pdf.add_page()
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(180, 0, 0)
            pdf.cell(0, 10, f"[Data rendering error in {name} section - Proceeding...]")

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()
